
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/toy_project
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
  # file upload setting
  servlet:
    multipart:
      max-file-size: 10MB  # ???? ?? 1?? ?? ??? ??
      max-request-size: 100MB  # ??? ???? ? ?? ??? ? ??

server:
  port: 9003

logging:
  level:
    com.spring.toyproject: DEBUG
    # SQL ??
    org.hibernate.SQL: DEBUG
    # ?? ???? ????
    org.springframework.web: DEBUG
    # SQL ???? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# jwt setting
jwt:
  # secret key (실제 운영에서는 환경변수로 관리)
  secret: MK/mhf3FIvBsuDfZfgDyJddADRHxqSRn3QLWE6B2Nvs=
  # 만료시간 (밀리초) - 24시간
  expiration: 86400000

# 파일 업로드 루트 경로 설정
file:
  upload:
    location: ${user.home}/travels/uploads/